/********** USER ACTION TYPES *************** */
export const SET_USER_IS_AUTH = "SET_USER_IS_AUTH";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_USER_INFO = "SET_USER_INFO";
export const UPDATE_USER = "UPDATE_USER";
export const USER_UPDATING = "USER_UPDATING";
export const SET_SCHOOLS = "SET_SCHOOLS";

/********** FETCH ACTION TYPES *************** */
export const FETCH_START = "FETCH_START";
export const FETCH_SET_MESSAGE = "FETCH_SET_MESSAGE";
export const FETCH_END = "FETCH_END";

/********** PRODUCT ACTION TYPES *************** */
export const SET_PRODUCTS_UPLOADS = "SET_PRODUCTS_UPLOADS";
export const DELETE_PRODUCTS_UPLOADS = "DELETE_PRODUCTS_UPLOADS";
export const SET_PRODUCTS_PURCHASES = "SET_PRODUCTS_PURCHASES";
export const SET_PRODUCTS_WISHLIST = "SET_PRODUCTS_WISHLIST";
export const ADD_PRODUCTS_WISHLIST = "ADD_PRODUCTS_WISHLIST";
export const DELETE_PRODUCT_FROM_WISHLIST = "DELETE_PRODUCT_FROM_WISHLIST";
export const PRODUCT_IS_EDITING = "PRODUCT_IS_EDITING";
export const PRODUCT_TO_EDIT_ID = "PRODUCT_TO_EDIT_ID";
export const SET_PRODUCTS_FILTERS = "SET_PRODUCTS_FILTERS";
export const SET_POPULATIONS = "SET_POPULATIONS";

/********** NOTIFICATIONS ACTION TYPES *************** */
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";

/********** CATEGORIES ACTION TYPES *************** */
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORIES_LIST = "SET_CATEGORIES_LIST";

/********** CART ACTION TYPES *************** */
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DELETE_ALL_FROM_CART = "DELETE_ALL_FROM_CART";
